name: Clean Jupyter notebooks

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
